database-type: 1

database-server-settings:
  host: "localhost"
  port: 0
  user: ""
  password: ""
  id: 0

# 是否使用多線程來處理命令(即使用命令不卡服. 但可能由於數據庫查詢原因造成(1~5秒的)延遲.)
# 如果妳不是很理解這段話, 請不要修改.
# 默認: true
command-threaded: true

# 第壹種貨幣
# 默認: Coin
money-unit-1: "Coin"

# 是否開啟第二種貨幣
# 如果設置為 false, 任何關於第二種貨幣的功能將禁止使用.
# 默認: true
enable-unit-2: true

# 第二種貨幣. (只有第壹種貨幣才能存入銀行)
# 默認: Point
money-unit-2: "Point"

# 銀行利息
# 默認: 0.0003
bank-interest-value: "0.0003"

# 銀行利息計算時間. (真實時間) (單位秒)
# 默認 86400 (24小時)
bank-interest-time: "86400"

# 請勿修改此項.
bank-time: "0"

# 玩家第壹次進服的初始第壹種貨幣數量
# 默認 1000
initial-money-1: "1000"

# 玩家第壹次進服的初始第二種貨幣數量
# 默認 0
initial-money-2: "0"

# 玩家第壹次進服的初始銀行儲蓄
# 默認 0
initial-bank-money: "0"

# 支付第壹種貨幣時, 玩家最低剩余值
# 默認 1000
pay-1-limit: "1000"

# 支付第二種貨幣時, 玩家最低剩余值
# 默認 1000
pay-2-limit: "1000"