# 是否使用多线程来处理命令(即使用命令不卡服. 但可能由于数据库查询原因造成(1~5秒的)延迟.)
# 如果你不是很理解这段话, 请不要修改.
# 默认: false
command-threaded: false

# 货币 1 名称
# 默认: Coin
money-unit-1: "Coin"

# 是否开启货币 2
# 如果设置为 false, 任何关于货币2的功能将禁止使用.
# 默认: true
enable-unit-2: true

# 货币 2 名称 (只有货币1才能存入银行)
# 默认: Point
money-unit-2: "Point"

# 银行利率
# 默认: 0.0003
bank-interest-value: "0.0003"

# 银行利息发放间隔. (真实时间) (单位秒)
# 默认 86400 (24小时)
bank-interest-time: "86400"

# 请勿修改此项.
bank-time: "0"

# 玩家第一次进服的初始货币1数量
# 默认 1000
initial-money-1: "1000"

# 玩家第一次进服的初始货币2数量
# 默认 0
initial-money-2: "0"

# 玩家第一次进服的初始银行储蓄
# 默认 0
initial-bank-money: "0"

# 支付货币1时, 玩家最低剩余值
# 默认 1000
pay-1-limit: "1000"

# 支付货币2时, 玩家最低剩余值
# 默认 1000
pay-2-limit: "1000"